# Generated by Django 2.2.7 on 2019-11-27 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_ratings', '0002_auto_20191127_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='rating',
        ),
    ]
