# Generated by Django 2.2.7 on 2019-11-27 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_ratings', '0003_remove_rating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
